felixedel/dotfiles

zsh/.aliases

For whatever reason the colored output in the ls command was gone. After
trying various things, calling ls with the --color option did the trick.
Not sure why this wasn't the case before. It doesn't look like any aliases
(oh-my-zsh, tmux, ...) have changed in the meantime.

Reactivate ls colors

---

zsh/.functions

If the venv could not be found there, it will fallback to
~/.virtualenvs/<venv>

zsh: Venv() function now searchs in project's .tox directory first

---

README.md
iterm2/com.googlecode.iterm2.plist
tmux/.tmux.conf
zsh/.exports
zsh/.zshrc

Changes:
9ce2c45 (Felix Schmidt, 4 weeks ago)
zsh: Set necessary envvars to show (custom) python venv prompt
69bb71a (Felix Schmidt, 4 weeks ago)
iterm2: Update color scheme and font type
b0f970d (Felix Schmidt, 4 weeks ago)
Update README including new font for python venv prompt
a71ad7d (Felix Schmidt, 4 weeks ago)
tmux: Fix background color of current status bar segment
c065d9d (Felix Schmidt, 4 weeks ago)
readme: Add some useful links
1feb5aa (Felix Schmidt, 4 weeks ago)
readme: Clone zsh plugin repos and describe necessary iterm2 settings
0a2e73b (Felix Schmidt, 5 weeks ago)
zsh: Add autosuggestions plugin
4f19379 (Felix Schmidt, 5 weeks ago)
zsh: Set DEFAULT_USER envvar to shorten command prompt in agnoster theme
2081fb4 (Felix Schmidt, 5 weeks ago)
zsh: Use agnoster theme

New tmux design based on agnoster theme

---

zsh/.aliases
zsh/.exports

38e7cd1 (Felix Schmidt, 46 seconds ago)
vscode: Alias to start vscode in the current directory by default
dc4200c (Felix Schmidt, 73 seconds ago)
vscode: Add vscode binary to PATH to enable start from command line

Start vscode from command line

---

vscode/settings.json

Changes:
4bfad7b (Felix Schmidt, 46 seconds ago)
vscode: Restructure global settings
5eea60f (Felix Schmidt, 8 minutes ago)
vscode: Set default python path in global config
Currently, vscode is complaining for every new project about the missing 
python path. So let's define the path that matches most of the projects as
default. If it doesn't work for a specific project, we might overwrite it
in that project's workspace config.
d628387 (Felix Schmidt, 9 minutes ago)
vscode: Activate flake8 with custom path in global config
0e57b4b (Felix Schmidt, 9 minutes ago)
vscode: Activate black with custom path in global config

vscode: Include pythonPath, black and flake8 in global config, restructure config keys

---

vscode/settings.json

Changes:
d51081b (Felix Schmidt, 2 minutes ago)
vscode: Deactivate split view for workspace settings
I usually already have an active split view and thus the splitted settings
view results in two very narrow windows.
70c052d (Felix Schmidt, 34 minutes ago)
vscode: Hide variables and modules in code outline
For larger files, those fill up the outline quite heavily and in most cases
don't provide too much information.
a4d16ee (Felix Schmidt, 35 minutes ago)
vscode: Enable editor rulers (vertical lines) for python files

Improve some vscode settings for python

---

vscode/settings.json

It's annoying when you just want to check some file contents and
whenever you close a file, the file explorer jumps to the next active
file.

vscode: Prevent file explorer from jumping to the active file

---

vscode/settings.json

On my native mac screen, I have exactly 85 characters available per pane
when two are open in vertical split. Thus, change this back to 80, so we
don't have to scroll horizontally all the time to get the remaining 5
characters.
For Python (where I'm also using 90) that's not a big problem, as only a
few lines every reach the limit, but for plain text in markdown, this
occurs much more often.

🔨 vscode: Change markdown ruler to 80

---

bin/dotfiles.sh

Didn't use that for a long time and just noticed that it's not
compatible to Python 3. There is a new version out which needs some
other setup steps first. So for now, just remove it from pipx.

➖ dotfiles: Remove aws

---

README.md
zsh/.zshrc
zsh/themes/felixedel.zsh-theme

Setting up a new dev machine feels like the right time to get a new
prompt. I like the minimalistic design of ZSH's default prompt, but
coming from the agnoster theme, I might miss a few information. Thus,
this changes adds a custom prompt based on the default one (robyrussel),
but adds a few features from the agnoster theme like:
- Show the relative path to the current dir based on the active git
root, the home directory or root (/)
- Show the active virtualenv and aws profile in a right prompt
- Show the branch/commit in different colors based on the state of the
repostory (clean, untracked files, local changes).
- Show the active git mode (rebase, cherry-pick, merge, ...)

Write a custom ZSH theme

---

zsh/.aliases

This breaks running python in git, e.g. during an interactive rebase by
using
$ rebase -i master --exec "tox -e linters"
as the locale setting is not fully qualified (the charset is missing).
I once had to overwrite the locale for the git command as it was always
showing the german command output not matter which locale was defined on
the system. By now, it looks like it's not needed anymore, so we are
just fine removing this.

zsh: Remove the git alias

---

git/.gitconfig

This caches solved merge conflicts and automatically applies the
solution when the same conflict comes up again. Might come in handy when
rebasing the same stack of changes again and again (which I'm currently
doing most of the time).

git: Enable rerere

---

zsh/.aliases

When bootstrapping up a new develment machine or when something is wrong
with colorls (very rarely the case), it's helpful to have at least the
"ls" command still working without having to adapt the zsh config.
Since I'm anyways using the "ll" alias in 99% of the time, it doesn't
harm to switch the ls command back to system defaults.

zsh: Remove "ls" alias for colorls

---

vscode/settings.json

This looks a little cluttered and I find it hard to focus on the active
tab (which is sometimes hard to identify).

code: Remove badges in tab decorations

---

vscode/settings.json

In some projects I find it more helpful to directly see when the change
was committed (and thus merged/active) rather than when it was
originally created.
Especially for projects where the roundtrip time of a change is longer.

vscode: Show the commit date in the gitlens inline commit view

---

.osxdefaults
README.md
iterm2/com.googlecode.iterm2.plist
vscode/settings.json
zsh/.exports

- zsh: Add ARM homebrew binaries to path
- macos: Clean defaults file
- vscode: Remove deprecated python interpreter setting
- vscode: Specify html default formatter
- Provide a list of installed vscode plugins in README
- vscode: Increase default font size (zoom level)
- iterm: Update settings
- iterm: Allow clipboard access

Updates for m1 mac

---

vscode/settings.json

This is useful to see the current line length and the vim search string
when in zen mode.

vscode: Show status bar in zen mode

---

README.md
zsh/.exports

The OpenSSL version provided by Mac OS is quite outdated. Use brew to
install a newer version.

Install openssl 1.1 via brew

---

.osxdefaults

It looks like the configuration via the Settings UI in Mac OS is now
sufficient, so there is no need to set anything beside that.

macos: Don't set mouse pointer speed via osxdefaults

---

README.md
bin/dotfiles.sh
zsh/.aliases

Exa[1] is a replacement for ls and built in rust. It is also shipped
with brew on Mac OS so there is no need or additional requirements like
ruby or gem (like colorls).
[1]: https://github.com/ogham/exa

Use exa instead of colorls

---

README.md
zsh/.aliases

I just found out that exa is not maintained anymore and one should
switch to eza instead [[1]](https://github.com/ogham/exa/commit/fb05c421ae98e076989eb6e8b1bcf42c07c1d0fe).

Switch to eza

---

vscode/settings.json

This takes up a lot of space and doesn't provide any benefit over using
cmd+p or shift+cmd+p.

vscode: Hide command center (search field on top)

---

README.md
zsh/.exports

There is also no need to add the python installation to the path as this
is already done by brew. I think I needed this after switching to the M1
mac in the first place, but maybe this is now included in brew directly.

Install python3.11 via brew

---

README.md
vscode/settings.json

See guide: https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions

vscode: Migrate to black and flake8 extensions

---

tig/.tigrc

By default, tig uses case sensitive search, which can be quite annoying
as you often don't know if a word is written with a capital letter or
not.

tig: Use smart-case search

---

.osxdefaults

This doesn't work as expected as auto-correction is always re-enabled
when starting the Notes app. However, in the meantime I found the
setting in the UI to disable that for now.

macos: Remove autocorrection default setting

---

vscode/settings.json

Zen mode looks kind of messy with a lot of tabs open. Usually only the
open tab was visible, but it looks like the default was changed some
time ago to show all tabs (like in normal mode).
However, there is now also the option to completely hide the tabs, which
is what I'm going for.

vscode: Don't show any tabs in zen mode

---

README.md
vscode/settings.json

Also update the VS Code Plugin list in the README.md file.

vscode: Set default python interpreter

---

vscode/settings.json

Using the vimrc fails breaks some use cases with the vim plugin in
vscode. I don't feel like debugging this now, so let's just revert this
and play around with it some other time.

Revert: "vscode: Use vim settings from ~/.vimrc file"
